name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug']
projects: ['mcraig0602/3']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report.

  # General bug summary
  - type: input
    id: short_desc
    attributes:
      label: Short Description
      description: A short description of the problem being reported
      placeholder: eg. A clear and concise description of what the bug is.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: The severity of the bug
      options:
        - 'Critical'
        - 'High'
        - 'Medium'
        - 'Low'
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App Version / Commit Hash
      description: The version of the app or the Git commit hash where the bug was found.
      placeholder: e.g. v1.2.3 or abc1234
    validations:
      required: false

  # Steps and behavior
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: |
        A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        ![Screenshot](url)
    validations:
      required: false

  # Platform and environment
  - type: checkboxes
    id: affected_platforms
    attributes:
      label: Affected Platforms
      description: The platforms affected by the bug
      options:
        - label: 'Windows'
        - label: 'macOS'
        - label: 'Linux'
        - label: 'iOS'
        - label: 'Android'

  - type: input
    id: desktop_info
    attributes:
      label: Desktop (please complete the following information)
      description: |
        OS, browser, and version (e.g. OS: Windows 11, Browser: Chrome, Version: 123)
      placeholder: |
        OS: [e.g. Windows 11]
        Browser: [e.g. Chrome, Safari]
        Version: [e.g. 123]
    validations:
      required: false

  - type: input
    id: smartphone_info
    attributes:
      label: Smartphone (please complete the following information)
      description: |
        Device, OS, browser, and version (e.g. Device: iPhone 12, OS: iOS 17, Browser: Safari, Version: 123)
      placeholder: |
        Device: [e.g. iPhone 12]
        OS: [e.g. iOS 17]
        Browser: [e.g. Safari]
        Version: [e.g. 123]
    validations:
      required: false

  # User impact
  - type: input
    id: affected_users
    attributes:
      label: Affected User(s)
      description: Please specify the username(s), email(s), or user group(s) affected by this bug (if applicable).
      placeholder: e.g. johndoe, jane@example.com, all users, admin group
    validations:
      required: false

  - type: checkboxes
    id: affected_user_type
    attributes:
      label: Affected User Type
      description: Select the type(s) of user affected by this bug.
      options:
        - label: 'Administrator'
        - label: 'Inspector'
        - label: 'User'

  # Context and references
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add any other context about the problem here.
    validations:
      required: false

  - type: input
    id: related_issues
    attributes:
      label: Related Issues or Pull Requests
      description: Reference any related issues or PRs (e.g. #123).
      placeholder: e.g. #123, #456
    validations:
      required: false

  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this functionality work in a previous version?
      options:
        - 'Yes'
        - 'No'
        - 'Not sure'
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output or Console Errors
      description: Paste any relevant logs, error messages, or stack traces here.
      placeholder: |
        Paste logs or error messages here.
    validations:
      required: false