name: Bug Report on Issue Creation

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read
  projects: write

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `
              mutation ($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item { id }
                }
              }
            `;

            // Replace with your actual Project ID (v2)
            const projectId = "PVT_kwHOANUy3c4A42jt";

            // Get the global ID of the issue
            const issueId = context.payload.issue.node_id;

            await github.graphql(query, {
              projectId: projectId,
              contentId: issueId
            });

            console.log(`Added issue #${context.issue.number} to project`);